### PR TITLE
Open in new window.

### LINKED ISSUE #7: ADD option to open urls in separate new windows
ADD option to open urls in separate new windows

### PR DESCRIPTION
**Pull request by jtagcat**
Next time, comment your code more please.

Tested on Firefox and Chrome.

Closes #7 

I am ok to take over and become a maintainer.

### CODE REVIEW

**Comment by jtagcat** [comment]
Closes #11 
Closes #13

**Comment by jtagcat** [comment]
Closes #8

**Comment by jtagcat** [comment]
Closes #15

**Comment by jtagcat** [comment]
#15 broken again

**Comment by jtagcat** [comment]
- need to find out, why alternative regex doesn't work

**Comment by htrinter** [comment]
Hello jtagcat, thank you for your contribution! I will do my best to review within the upcoming weeks.

In regard to taking over: The extension has >130.000 users, I feel responsible for providing a stable version of the extension to them. Additionally, to me the extension is nearly feature-complete. For these reasons I would rather you fork the project.

**Comment by jtagcat** [comment]
> Hello jtagcat, thank you for your contribution! I will do my best to review within the upcoming weeks.
> 
> In regard to taking over: The extension has >130.000 users, I feel responsible for providing a stable version of the extension to them. Additionally, to me the extension is nearly feature-complete. For these reasons I would rather you fork the project.

As long as you keep active on PRs ;)

Regex and settings sync is not fully complete.

I think I finished regex, but need to cleanup, sync should in theory work, but I have to find a way to test it on both chrome and ff so the settings actually keep themselves (by current testing, when you check the sync storage, you will get 'true' for everything).

**Comment by jtagcat** [comment]
Note to self: https://extensionworkshop.com/documentation/develop/testing-persistent-and-restart-features/

**Comment by jtagcat** [comment]
Couldn't get it to work in 40 minutes, reverting sync mechanism to the one currently in master. Firefox support (#15) remains broken.

As for regex, [current](https://regexr.com/4uv7b) vs [the gold standard compatible with standards](https://regexr.com/4uv78) (from [SO](https://stackoverflow.com/a/190405/12470046)). There's problems with escaping and stuff, I'm not very exited to fix it.

The MR should be ready to merge.

**Comment by jtagcat** [comment]
I apologize for this pull. I should've talked to you more and made smaller pulls; instead of trying to do everything within days of working on the same thing.

Since I'm already somewhat familiar, I'll try again some time. When is some time, I don't know.

**Pull request closed without merging**
